### ISSUE TITLE
namespaced includes

### ISSUE THREAD

**Issue by larshp** [SAP/ewm-cloud-robotics-s4#1]
Hi,
There are some namespaced includes in the function group, eg https://github.com/SAP/ewm-cloud-robotics-s4/blob/master/abap/zewm_rf_robco.fugr.%23scwm%23lrf_sscri01.abap, should these be renamed to customer Z namespace?

**Comment by oliver-goetz** [comment]
Thanks for the hint. I did not notice that they were copied here. These are some elements from SAP screens we reused. Is there a way to exclude them from abapGit? I don't want to copy them, they should be in target systems anyhow.

**Comment by larshp** [comment]
If only the FORMs are needed, then do `PERFORM foo IN PROGRAM bar`.

abapGit takes all the includes from the function group, you can decide not to push the files to git, but it will show up in the staging list every time

https://help.sap.com/doc/abapdocu_751_index_htm/7.51/en-us/abenmultiple_use_include_guidl.htm

**Comment by oliver-goetz** [comment]
Afaik just reusing the forms from the foreign program won't work and refactoring is too complex to get done on short notice. Thus, I removed the foreign include files and cleaned up the repository for now.

**Comment by larshp** [comment]
cool, closing 👍
