### ISSUE TITLE
software components

### ISSUE THREAD

**Issue by larshp** [SAP/ewm-cloud-robotics-s4#2]
just a tip, under "repo settings" its possible to define specific software components that are required, so if users try to install the code on a system without the component abapGit will show an error.

![image](https://user-images.githubusercontent.com/5888506/60896770-31a8fb80-a267-11e9-9a64-140bd0f84d60.png)

**Comment by oliver-goetz** [comment]
Is it possible to add another github repository as requirement? The code of this repository depends on https://github.com/SAP/ewm-cloud-robotics

**Comment by larshp** [comment]
no, not yet, see https://github.com/larshp/abapGit/issues/217

**Comment by oliver-goetz** [comment]
ok, I keep this in mind for the time when it is done
